DROP TABLE IF EXISTS User;

CREATE TABLE IF NOT EXISTS Users (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    Active BOOLEAN NOT NULL,
    Name VARCHAR(150) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Password VARCHAR(2000) NOT NULL
);

